
module.exports = {
    ADD_SUCCESS: 'Add Successfully',
    EDIT_SUCCESS: 'Edit Successfully',
    ERROR_NAME: 'Name length must be from %d to %d',
    ERROR_NAME_EMPTY: 'Name must be non-empty',
    ERROR_NAME_DUPLICATED: 'Duplicated Name',
    ERROR_TITLE: 'Title length must be from %d to %d',
    ERROR_TITLE_EMPTY: 'Title must be non-empty',
    ERROR_TITLE_DUPLICATED: 'Duplicated Title',
    ERROR_ORDERING: 'Ordering must be number from %d to %d',
    ERROR_QUANTITY: 'Quantity must be number from %d',
    ERROR_STATUS: 'Status must be choose',
    ERROR_CATEGORY: "Category must be choose",
    ERROR_CATEGORY_INVALID: "Category is invalid",
    ERROR_SLUG: 'Invalid Slug',
    ERROR_SLUG_DUPLICATED: 'Duplicated Slug',
    ERROR_FILE_LIMIT: 'Invalid Size File',
    ERROR_FILE_EXTENSION: 'Invalid Type File',
    ERROR_FILE_EMPTY: 'Must upload photo',
    ERROR_DESCRIPTION: 'Description must be non-empty',
    ERROR_DETAIL: 'Detail must be non-empty',
    ERROR_SOURCE: 'Source must be non-empty',
    ERROR_SETTING_TITLEPAGE: 'Please input Title Page',
    ERROR_SETTING_ADDRESS: 'Please input Address',
    ERROR_SETTING_PHONENUMBER: 'Please input Phone Number',
    ERROR_SETTING_EMAIL: 'Please input valid Email',
    ERROR_SETTING_COPPYRIGHT: 'Please input Coppyright',
    ERROR_SETTING_URLFACEBOOK: 'Input link Facebook wrong',
    ERROR_SETTING_URLTWITTER:'Input link Twitter wrong',
    RROR_SETTING_URLINSTAGRAM:'Input link Instagram wrong',
    ERROR_SETTING_URLYOUTUBE:'Input link Youtube wrong',
    ERROR_SETTING_URLLINKEDIN:'Input link LinkedIN wrong',
    ERROR_SLIDER_URL:'Input link invalid',
    ERROR_RSS_URL:"Input link wrong",
    ERROR_SUBJECT: 'Subject must be non-empty',
    ERROR_API_EMPTY: 'API must be non-empty',
    ERROR_EMAIL: "Please input valid Email",
    ERROR_MESSAGE: "Please input Message",
    SUCCESS_SETTING_SAVE: 'Save Setting Successfully',
    ERROR_NOT_EXITS: 'Not Exits',
    ERROR_DISCOUNT_UNIT: 'Discount Value is Percent or Money',
    ERROR_DISCOUNT_MONEY: 'Money must be number from %d',
    ERROR_DISCOUNT_PERCENT: 'Money must be number from > %d to < %d',
    ERROR_DISCOUNT_LISTPRODUCT: 'List product must be non-empty',
    ERROR_DISCOUNT_LISTPRODUCT_INVALID:'List product invalid',
    ERROR_SLIDER_TEXTBUTTON: 'Text button length must be from %d to %d',
    ERROR_SLIDER_HEADERTITLE: 'Hearder title must be from %d to %d',
    ERROR_SLIDER_TITLE: 'Title must be from %d to %d',
    ERROR_SLIDER_DESCRIPTION: 'Desciption must be from %d to %d',
    ERROR_SETTING_SUBJECT_EMAIL: 'Subject Email length must be from %d',
    ERROR_SETTING_CONTENT_EMAIL: 'Content Email length must be from %d',
    ERROR_SETTING_TITLE_CLIENT: 'Title What Client Say must be non-empty',
    ERROR_SETTING_LIST_CLIENT: 'List Client Say must be non-empty',
    ERROR_SETTING_LIST_CLIENT_VALUE: 'List Client Say is invalid',
    ERROR_SETTING_LIST_MISSION: 'List Mission must be non-empty',
    ERROR_SETTING_LIST_MISSION_VALUE: 'List Mission is invalid',
    ERROR_SETTING_TITLE_ABOUTUS: 'Title of About US page must be non-empty',
    ERROR_SETTING_CONTENT_ABOUTUS: 'Content of About US page must be non-empty',
    ERROR_SETTING_DATA_ABOUTUS: 'Data of About US page must be number',
};
